"""initial schema

Revision ID: 72b3332a736a
Revises: 
Create Date: 2026-09-12 19:13:27.597524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72b3332a736a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=False),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('reply_to', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('smtp_host', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('smtp_port', sa.Integer(), server_default=sa.text('587'), nullable=True),
    sa.Column('smtp_username', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('smtp_secret_encrypted', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('imap_host', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('imap_port', sa.Integer(), server_default=sa.text('993'), nullable=True),
    sa.Column('imap_username', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('imap_secret_encrypted', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('use_tls', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('daily_send_limit', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('hourly_send_limit', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('last_test_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hunt_id', sa.String(), nullable=False),
    sa.Column('email_account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('language_mode', sa.String(), server_default=sa.text("'auto_by_region'"), nullable=False),
    sa.Column('default_language', sa.String(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('fallback_language', sa.String(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('tone', sa.String(), server_default=sa.text("'professional'"), nullable=False),
    sa.Column('step1_delay_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('step2_delay_days', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('step3_delay_days', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('min_fit_score', sa.Float(), server_default=sa.text('0.6'), nullable=False),
    sa.Column('min_contactability_score', sa.Float(), server_default=sa.text('0.45'), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_campaigns_hunt', 'email_campaigns', ['hunt_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sequence_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('scheduled_at', sa.String(), nullable=False),
    sa.Column('sent_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('provider_message_id', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('thread_key', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('failure_reason', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'step_number', name='uq_email_message_sequence_step')
    )
    op.create_index('idx_email_message_status_schedule', 'email_messages', ['status', 'scheduled_at'], unique=False)
    op.create_index('idx_email_messages_sequence', 'email_messages', ['sequence_id'], unique=False)
    op.create_table('email_reply_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sequence_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('subject', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('snippet', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('received_at', sa.String(), nullable=False),
    sa.Column('raw_ref', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reply_sequence_id', 'email_reply_events', ['sequence_id'], unique=False)
    op.create_table('hunt_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('available_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('finished_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('claimed_by', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('last_hunt_id', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('progress_stage', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('progress_message', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('template_seed_status', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('template_seed_source', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hunt_jobs_status_available', 'hunt_jobs', ['status', 'available_at', 'created_at'], unique=False)
    op.create_table('hunts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('current_stage', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('hunt_round', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('leads_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('email_sequences_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('website_url', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hunts_status', 'hunts', ['status', 'created_at'], unique=False)
    op.create_table('lead_email_sequences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('hunt_id', sa.String(), nullable=False),
    sa.Column('lead_key', sa.String(), nullable=False),
    sa.Column('lead_email', sa.String(), nullable=False),
    sa.Column('lead_name', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('decision_maker_name', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('decision_maker_title', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('locale', sa.String(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('generation_mode', sa.String(), server_default=sa.text("'personalized'"), nullable=False),
    sa.Column('template_id', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('template_group', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('template_usage_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('template_max_send_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('current_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stop_reason', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('replied_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('last_sent_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('next_scheduled_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'lead_key', name='uq_sequence_campaign_lead')
    )
    op.create_index('idx_sequences_campaign', 'lead_email_sequences', ['campaign_id'], unique=False)
    op.create_index('idx_sequences_lead_key', 'lead_email_sequences', ['lead_key'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_key', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('company_name', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('website', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('industry', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('country_code', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('address', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('phone_numbers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('social_media', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('decision_makers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('customs_data', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('match_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('fit_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('contactability_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('priority_tier', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('first_seen_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('last_seen_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('seen_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('first_hunt_id', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('last_hunt_id', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_key')
    )
    op.create_index('idx_leads_company_name', 'leads', ['company_name'], unique=False)
    op.create_index('idx_leads_domain', 'leads', ['domain'], unique=False)
    op.create_index('idx_leads_last_seen', 'leads', ['last_seen_at'], unique=False)
    op.create_table('hunt_leads',
    sa.Column('hunt_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('reused', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('added_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hunt_id', 'lead_id')
    )
    op.create_index('idx_hunt_leads_hunt', 'hunt_leads', ['hunt_id'], unique=False)
    op.create_table('lead_sightings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('hunt_id', sa.String(), nullable=False),
    sa.Column('source_keyword', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('seen_at', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'hunt_id', 'source_keyword', name='uq_lead_sighting')
    )
    op.create_index('idx_lead_sightings_hunt', 'lead_sightings', ['hunt_id'], unique=False)
    op.create_index('idx_lead_sightings_lead', 'lead_sightings', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lead_sightings_lead', table_name='lead_sightings')
    op.drop_index('idx_lead_sightings_hunt', table_name='lead_sightings')
    op.drop_table('lead_sightings')
    op.drop_index('idx_hunt_leads_hunt', table_name='hunt_leads')
    op.drop_table('hunt_leads')
    op.drop_index('idx_leads_last_seen', table_name='leads')
    op.drop_index('idx_leads_domain', table_name='leads')
    op.drop_index('idx_leads_company_name', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_sequences_lead_key', table_name='lead_email_sequences')
    op.drop_index('idx_sequences_campaign', table_name='lead_email_sequences')
    op.drop_table('lead_email_sequences')
    op.drop_index('idx_hunts_status', table_name='hunts')
    op.drop_table('hunts')
    op.drop_index('idx_hunt_jobs_status_available', table_name='hunt_jobs')
    op.drop_table('hunt_jobs')
    op.drop_index('idx_reply_sequence_id', table_name='email_reply_events')
    op.drop_table('email_reply_events')
    op.drop_index('idx_email_messages_sequence', table_name='email_messages')
    op.drop_index('idx_email_message_status_schedule', table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index('idx_email_campaigns_hunt', table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
